
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Mobilek
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.Cars = new HashSet<Car>();

    }


    public int Id { get; set; }

    public int carsId { get; set; }

    public int customerId { get; set; }

    public System.DateTime startDate { get; set; }

    public System.DateTime endDate { get; set; }

    public int returnStationId { get; set; }

    public int workerId { get; set; }

    public bool isFinished { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Station Station { get; set; }

    public virtual Worker Worker { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Car> Cars { get; set; }

}

}
